[project]
name = "pdf-converter-03"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marker-pdf>=1.10.1",
    "openai>=1.109.1",
    "pyright>=1.1.407",
]
